spring:
  application:
    name: gym-crm
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  liquibase:
    change-log: classpath:db/changelog/changelog-root.xml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  servlet:
    context-path: /gym-crm
  port: 8080

app:
  api:
    base-path: /api/v1
