storage.init.trainee=classpath:data/trainee.csv
storage.init.trainer=classpath:data/trainer.csv
storage.init.training=classpath:data/training.csv

datasource.jdbc-url=${DB_URL:jdbc:mysql://localhost:3306/gym_db}
datasource.username=${DB_USERNAME:changeit}
datasource.password=${DB_PASSWORD:changeit}

datasource.hikari.maxPoolSize=10
datasource.hikari.minIdle=2
datasource.hikari.connectionTimeout=30000
datasource.hikari.idleTimeout=600000
datasource.hikari.maxLifetime=1800000

hibernate.hbm2ddl-auto=none
hibernate.show-sql=false
hibernate.format-sql=false
